### ISSUE TITLE
why not see the data_combined？

### ISSUE THREAD

**Issue by tiankong1993** [jindongwang/activityrecognition#1]
Hi,where are the data_combined of the line of FeatureExtraction2?

**Comment by jindongwang** [comment]
Hi there, thank you for pointing it out! That's my mistake. I've already changed it in the latest commit.
Actually the data_combined in my code refers to combining 3 axis of the accelerometer data together using  square root like a=sqrt(ax^2+ay^2+az^2). When you are using this code, you can pass any data (vector of a fixed window perhaps) to the function.
