### ISSUE TITLE
数据格式问题

### ISSUE THREAD

**Issue by HaoWangDL** [jindongwang/activityrecognition#2]
王博士，你好

       6轴陀螺仪和加速度计提取特征，数据格式应该是怎么样的呢？

**Comment by jindongwang** [comment]
@HaoWangDL 我们一般采用的数据格式：
一个大小为 M * (N + 1) 的矩阵，其中：
- M：数据样本的个数
- N：数据维度，比如你说的6轴，那么这里N=6
- 1：标签，比如走路是1，坐是2，等等

**Comment by HaoWangDL** [comment]
您的代码很详细，也可以看出数据格式。

如果我做运动类型识别，比如踢腿（横踢、侧踢、后踢等），您这有什么好的研究思路吗？
谢谢

**Comment by jindongwang** [comment]
这个感觉是一个很正常的分类任务，先收集数据做个简单的模型看一下？

**Comment by HaoWangDL** [comment]
恩，是一个多分类任务。通过六轴采集数据，特征提取用的您的脚本，提取了27*6个特征，通过feature selection方法筛出来50个特征，效果不是太好，正在查找原因。

**Comment by jindongwang** [comment]
可能是：
1. 特征提的不够多？是否遗漏了什么特征？
2. 提完特征构建模型是否进行了归一化？
3. 用的什么模型，是否可以换别的试一下？

**Comment by jindongwang** [comment]
@HaoWangDL 刚看到的一个开源时间序列库：https://arxiv.org/abs/1803.08118，你可以参考

**Comment by HaoWangDL** [comment]
谢谢王博士，我学习学习
