### ISSUE TITLE
FFT特征提取问题

### ISSUE THREAD

**Issue by mingmin95** [jindongwang/activityrecognition#4]
你好，刚接触信号处理，看了你的代码，对于频域特征提取几点问题想要请教：
1、你有说过窗口大小必须是2的指数倍，傅里叶变换才能才能顺利进行，可在使用python的np.fft函数时并没有体现这一点
2、你在计算形状统计特征的均值时，freq_spectrum分量乘的系数是0,1,2,...n-1,是不是应该乘以1,2,3,,,,n

**Comment by mingmin95** [comment]
3、fft特征提取是一般只留fft变换后一半的点进行分析吗

**Comment by jindongwang** [comment]
@mm1352363 
1. 我们通常倾向于选择窗口大小为2的指数倍，这样效果会比较好，并不是说只能选择这个数，习惯问题；
2. 这个差别不大
3. 傅里叶变换以后的数据是左右对称的，所以可以只保留一半。你做一个看看就知道了

**Comment by jindongwang** [comment]
@mm1352363 这个python库你可以直接用：https://dmbee.github.io/seglearn/feature_functions.html

**Comment by mingmin95** [comment]
谢谢，我简单看了一下，这个好像是计算时间序列特征的库，我现在要对加速度信息的时域和频域的特征进行提取，另外我刚才看了一下skewness是对统计数据偏斜程度的度量，虽然傅里叶变换后的数据是左右对称，但保留一半计算出来的特征是不是有可能没有全部使用计算出的特征效果好呢

**Comment by jindongwang** [comment]
你想保留就保留吧。。。反正也要进行特征选择和降维
