### ISSUE TITLE
tsfeatures時間序列特徵提取問題

### ISSUE THREAD

**Issue by yanwu0105** [jindongwang/activityrecognition#6]
大神您好，
目前在R語言上有search到這個套件，主要也是做時間序列上的特徵提取，不知道您這個套件與他是否相似？
https://github.com/robjhyndman/tsfeatures

**Comment by jindongwang** [comment]
可能相似吧，毕竟这些feature来来去去都是那些。找一个自己熟悉的用就可以。


在2019年01月3日 17:47，Yanhei Wu<notifications@github.com><mailto:notifications@github.com> 写道：

大神您好，
目前在R語言上有search到這個套件，主要也是做時間序列上的特徵提取，不知道您這個套件與他是否相似？
https://github.com/robjhyndman/tsfeatures
