### ISSUE TITLE
ActivityRecognition and ActionRecognition

### ISSUE THREAD

**Issue by Amazingren** [jindongwang/activityrecognition#9]
Hello, and I'm sorry for disturbing you.But I really want to know the difference between Activity Recognition and Action Recognition? Could you please show me some lights on?
Thank you so much!~~~

**Comment by jindongwang** [comment]
Sorry for the late reply.
We often use action recognition to refer to the video or camera-based recognition, while activity recognition refers to sensor-based recognition.
